services: 

  # mysql gestion de base de datos
  mysql: 
    image: mysql:8.0 
    environment:  
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rolegames
    ports: 
      - "3307:3306"
    volumes: 
      - ./mysql-data/:/var/lib/mysql
    networks: 
      - rolegames-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]  
      interval: 10s
      timeout: 5s
      retries: 5
    
    #el back
  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rolegames-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports: 
      - "8080:8080"
    environment:
      # Configuración de base de datos
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rolegames?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      
      # Configuración JPA/Hibernate
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_SHOW_SQL: false
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      
      # Configuración de logging
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_KAL_COM_ROLEGAMES: DEBUG
      
      # Configuración de servidor
      SERVER_PORT: 8080
      
      # Configuración de JWT (opcional)
      APP_JWTSECRET: d82f17be37c62ac9397fd35dfa211e57079a0f459c5482d564309781b48adc91f8f9878750286db8c508fa932d5c0eb62a40f18419f7224f808c8517f32d6dc0
      APP_JWTEXPIRATIONINMS: 86400000
    volumes:
      - ./backend:/app
    networks: 
      - rolegames-network

#el front
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rolegames-frontend
    ports: 
      - "3000:3000"
    depends_on: 
      - backend
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    networks: 
      - rolegames-network
    environment:
      - VITE_API_URL=http://localhost:8080
      - NODE_ENV=development
    restart: unless-stopped
      
networks:
  rolegames-network:
    driver: bridge
