@echo off
echo ➡️  Entrando al directorio backend...
cd backend || (echo ❌ No se pudo acceder a backend & exit /b)

echo 🔙 Volviendo al directorio original...
cd ..

echo ⚙️  Ejecutando Gradle Wrapper...
call gradlew wrapper || (echo ❌ Error al ejecutar Gradle Wrapper & exit /b)

echo 🧹 Eliminando carpeta mysql-data...
rmdir /s /q mysql-data

echo 🐳 Levantando contenedores backend y mysql...
docker compose up -d backend mysql

echo 🧵 Abriendo nueva terminal para instalar librerías frontend...
start cmd /k "docker compose exec frontend sh -c \"npm install zustand react-toastify\""

echo 📄 Abriendo nueva terminal para mostrar documentación y URL del frontend...
start cmd /k "echo 🧾 Documentación de los servicios disponibles: & docker compose ps & echo. & echo 🌐 El frontend está disponible en: http://localhost:3000"

