package kal.com.rolegames.models.util;

public enum NotificationType {
    CAMPAIGN_INVITATION,
    SESSION_REMINDER,
    CHARACTER_LEVEL_UP,
    COMBAT_TURN,
    ITEM_OBTAINED,
    GENERAL_ANNOUNCEMENT,
    ENCOUNTER_CREATED,
    PLAYER_JOINED_CAMPAIGN,
    SESSION_SCHEDULED,
    COMBAT_STARTED,
    COMBAT_ENDED
}